// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: crumb.proto

package crumb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Crumb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index    int64  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hash     []byte `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	PrevHash []byte `protobuf:"bytes,4,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	Content  string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Crumb) Reset() {
	*x = Crumb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_crumb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Crumb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Crumb) ProtoMessage() {}

func (x *Crumb) ProtoReflect() protoreflect.Message {
	mi := &file_crumb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Crumb.ProtoReflect.Descriptor instead.
func (*Crumb) Descriptor() ([]byte, []int) {
	return file_crumb_proto_rawDescGZIP(), []int{0}
}

func (x *Crumb) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Crumb) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Crumb) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Crumb) GetPrevHash() []byte {
	if x != nil {
		return x.PrevHash
	}
	return nil
}

func (x *Crumb) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_crumb_proto protoreflect.FileDescriptor

var file_crumb_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x72, 0x75, 0x6d, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63,
	0x72, 0x75, 0x6d, 0x62, 0x22, 0x7c, 0x0a, 0x05, 0x43, 0x72, 0x75, 0x6d, 0x62, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x72, 0x65, 0x76, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x70, 0x72, 0x65, 0x76, 0x48, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x63, 0x72, 0x75, 0x6d, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_crumb_proto_rawDescOnce sync.Once
	file_crumb_proto_rawDescData = file_crumb_proto_rawDesc
)

func file_crumb_proto_rawDescGZIP() []byte {
	file_crumb_proto_rawDescOnce.Do(func() {
		file_crumb_proto_rawDescData = protoimpl.X.CompressGZIP(file_crumb_proto_rawDescData)
	})
	return file_crumb_proto_rawDescData
}

var file_crumb_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_crumb_proto_goTypes = []interface{}{
	(*Crumb)(nil), // 0: crumb.Crumb
}
var file_crumb_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_crumb_proto_init() }
func file_crumb_proto_init() {
	if File_crumb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_crumb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Crumb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_crumb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_crumb_proto_goTypes,
		DependencyIndexes: file_crumb_proto_depIdxs,
		MessageInfos:      file_crumb_proto_msgTypes,
	}.Build()
	File_crumb_proto = out.File
	file_crumb_proto_rawDesc = nil
	file_crumb_proto_goTypes = nil
	file_crumb_proto_depIdxs = nil
}
